# A Catppuccin RC file to element. In beta, specs may change. 
app_name: element
binary_name: element-desktop 
installation:
  hooks:
    pre:
      install: 
        - type: shell
        - args: ls -la
  location: 
    macos: ~/.config/Element/
    linux: ~/.config/Element/
    windows: "%appdata%/Element"
  flavours: 
    all:
      default: 
        - config.json
  to: .
  one_flavour: false 
  comments: "Something to do something"

