# A Catppuccin RC file to element. In beta, specs may change. 
app_name: element
binary_name: element-desktop 
installation:
  hooks:
    pre:
      install: 
      - type: browser
        args:
        - "https://github.com/catppuccin/catppuccin"
      uninstall:
      - type: shell 
        args: 
        - "ls"
    post:
      install:
      - type: shell 
        args: 
        - "ls"
      uninstall:
      - type: shell 
        args: 
        - "ls"
  location: 
    macos: ~/.config/Element/
    linux: ~/.config/Element/
    windows: "%appdata%/Element"
  flavours: 
    all:
      default: 
        - config.json
  to: .
  one_flavour: false 
  comments: "Something to do something"

